package com.moussefer.admin.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.reactive.function.client.WebClient;

import java.security.SecureRandom;
import java.time.Duration;
import java.util.Map;

/**
 * Admin-only user creation — primarily for ORGANIZER accounts which cannot self-register.
 *
 * PASSENGER and DRIVER use the public /api/v1/auth/register endpoint.
 * ORGANIZER accounts require manual creation by a SUPER_ADMIN through this endpoint.
 *
 * The AdminRoleGuard ensures only SUPER_ADMIN can reach this controller.
 */
@RestController
@RequestMapping("/api/v1/admin/users")
@RequiredArgsConstructor
@Slf4j
@Tag(name = "Admin – User Creation", description = "Create ORGANIZER or other admin-managed accounts")
public class AdminUserCreationController {

    private final WebClient authServiceWebClient;
    private static final Duration TIMEOUT = Duration.ofSeconds(5);

    /**
     * Create an ORGANIZER (or any role) account.
     *
     * Expected body:
     * {
     *   "email": "org@example.com",
     *   "password": "optional — auto-generated if omitted",
     *   "phoneNumber": "+21612345678",
     *   "role": "ORGANIZER"   // default
     * }
     *
     * Response includes the generated password if one was auto-created,
     * so the admin can share it with the new organizer.
     */
    @PostMapping
    @Operation(summary = "Create a new account (ORGANIZER by default, admin-only)")
    public ResponseEntity<Map<String, Object>> createUser(
            @RequestBody Map<String, Object> body,
            @RequestHeader("X-User-Id") String adminId) {
        String email = String.valueOf(body.getOrDefault("email", "")).trim();
        if (email.isBlank()) {
            return ResponseEntity.badRequest().body(Map.of("error", "email is required"));
        }

        Object rawPassword = body.get("password");
        String password = (rawPassword == null || String.valueOf(rawPassword).isBlank())
                ? generateSecurePassword()
                : String.valueOf(rawPassword);
        boolean autoGenerated = (rawPassword == null || String.valueOf(rawPassword).isBlank());

        String phoneNumber = body.get("phoneNumber") != null
                ? String.valueOf(body.get("phoneNumber")) : null;
        String role = String.valueOf(body.getOrDefault("role", "ORGANIZER")).toUpperCase();

        Map<String, Object> forward = new java.util.HashMap<>();
        forward.put("email", email);
        forward.put("password", password);
        forward.put("role", role);
        if (phoneNumber != null && !phoneNumber.isBlank()) forward.put("phoneNumber", phoneNumber);

        Map<String, Object> res;
        try {
            @SuppressWarnings("unchecked")
            Map<String, Object> response = authServiceWebClient.post()
                    .uri("/api/v1/auth/internal/admin/create-user")
                    .header("X-Admin-Id", adminId)
                    .bodyValue(forward)
                    .retrieve()
                    .bodyToMono(Map.class)
                    .block(TIMEOUT);
            res = response != null ? response : Map.of();
        } catch (Exception e) {
            log.error("Admin {} failed to create {} account for {}: {}", adminId, role, email, e.getMessage());
            return ResponseEntity.status(500).body(Map.of("error", "auth-service error", "details", e.getMessage()));
        }

        log.info("Admin {} created {} account: email={}", adminId, role, email);

        Map<String, Object> responseBody = new java.util.HashMap<>(res);
        if (autoGenerated) {
            responseBody.put("generatedPassword", password);
            responseBody.put("warning", "This password is shown ONCE. Share it with the user securely.");
        }
        return ResponseEntity.status(201).body(responseBody);
    }

    /**
     * Generates a readable 12-character password:
     * upper + lower + digit + symbol (at least one of each).
     */
    private String generateSecurePassword() {
        SecureRandom rnd = new SecureRandom();
        String upper = "ABCDEFGHJKLMNPQRSTUVWXYZ";      // no I, O
        String lower = "abcdefghjkmnpqrstuvwxyz";       // no i, l, o
        String digit = "23456789";                      // no 0, 1
        String symbol = "!@#$%&*";
        StringBuilder pw = new StringBuilder();
        pw.append(upper.charAt(rnd.nextInt(upper.length())));
        pw.append(lower.charAt(rnd.nextInt(lower.length())));
        pw.append(digit.charAt(rnd.nextInt(digit.length())));
        pw.append(symbol.charAt(rnd.nextInt(symbol.length())));
        String all = upper + lower + digit + symbol;
        for (int i = 0; i < 8; i++) pw.append(all.charAt(rnd.nextInt(all.length())));
        // light shuffle
        char[] arr = pw.toString().toCharArray();
        for (int i = arr.length - 1; i > 0; i--) {
            int j = rnd.nextInt(i + 1);
            char tmp = arr[i]; arr[i] = arr[j]; arr[j] = tmp;
        }
        return new String(arr);
    }
}
